server:
  port: 8085
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: noteHandler

  datasource:
    url: jdbc:postgresql://localhost:5432/notes_app
    username: db_notes
    password: db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true
